import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "sms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
